# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ 
  inputs,
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:
{
  imports = [ 
    (modulesPath + "/installer/scan/not-detected.nix")
    inputs.impermanence.nixosModules.impermanence
  ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "none";
      fsType = "tmpfs";
      neededForBoot = true;
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-partuuid/8053401b-2b60-4e5c-a10e-1fe8399e531b";
      fsType = "vfat";
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/abea99fa-060c-40e0-90fd-445b805e418e";
      fsType = "btrfs";
      options = [ "subvol=@nixos@nix" "relatime" "discard=async" "compress=zstd:1" ];
      neededForBoot = true;
    };

  fileSystems."/etc/NetworkManager" =
    { device = "/dev/disk/by-uuid/abea99fa-060c-40e0-90fd-445b805e418e";
      fsType = "btrfs";
      options = [ "subvol=@nixos@networkmanager-config" "relatime" "discard=async" "compress=zstd:1" ];
    };

  fileSystems."/persist" =
    { device = "/dev/disk/by-uuid/abea99fa-060c-40e0-90fd-445b805e418e";
      fsType = "btrfs";
      options = [ "subvol=@nixos@persist" "relatime" "discard=async" "compress=zstd:1" ];
      neededForBoot = true;
    };

  fileSystems."/root" =
    { device = "/dev/disk/by-uuid/abea99fa-060c-40e0-90fd-445b805e418e";
      fsType = "btrfs";
      options = [ "subvol=@nixos@root-user" "relatime" "discard=async" "compress=zstd:1" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/a20e2835-bad5-4976-85b7-379ca753f80d";
      fsType = "btrfs";
      options = [ "subvol=@nixos@home" "relatime" "discard=async" "compress=zstd" ];
    };

  fileSystems."/mnt/backup/128Gext" =
    { device = "/dev/disk/by-uuid/82a75835-a541-4976-bc10-d643a69169b6";
      fsType = "btrfs";
      options = [ "subvol=@backup" "relatime" "discard=async" "compress=zstd" "noauto" ];
    };

  fileSystems."/mnt/backup/256Gext" =
    { device = "/dev/disk/by-uuid/7dcad2e8-e127-4a55-9a41-f73c46239e9b";
      fsType = "btrfs";
      options = [ "subvol=@backup" "relatime" "discard=async" "compress=zstd" "noauto" ];
    };

  fileSystems."/mnt/btrfs_pool01" =
    { device = "/dev/disk/by-uuid/abea99fa-060c-40e0-90fd-445b805e418e";
      fsType = "btrfs";
      options = [ "subvol=/" "relatime" "discard=async" "compress=zstd:1" ];
    };

  fileSystems."/mnt/btrfs_pool02" =
    { device = "/dev/disk/by-uuid/a20e2835-bad5-4976-85b7-379ca753f80d";
      fsType = "btrfs";
      options = [ "subvol=/" "relatime" "discard=async" "compress=zstd" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # this folder is where the files will be stored (don't put it in tmpfs)
  environment.persistence."/persist" = {
    hideMounts = true;
    directories = [
      "/etc/ssh"
      "/var/log"
      "/var/lib/cups"
      "/var/lib/fprint"
      "/var/db/sudo/lectured"
    ];
    files = [
      "/etc/machine-id"
      "/etc/nix/id_rsa"
      "/var/lib/logrotate.status"
    ];
  };
}
