# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ 
  inputs
  , config
  , lib
  , pkgs
  , modulesPath
  , ... 
}:
#let
#  impermanence = builtins.fetchTarball "https://github.com/nix-community/impermanence/archive/master.tar.gz";
#in
{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
#      "${impermanence}/nixos.nix"
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" "sg" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "none";
      fsType = "tmpfs";
      neededForBoot = true;
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-partuuid/0194752a-6d74-40fb-b576-e15b1706062d";
      fsType = "vfat";
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/b89c65c8-f25a-4a18-a48b-5511e3dfd306";
      fsType = "btrfs";
      options = [ "subvol=@nixos@nix" "relatime" "discard=async" "compress=zstd:1" ];
      neededForBoot = true;
    };

  fileSystems."/etc/nixos" =
    { device = "/dev/disk/by-uuid/b89c65c8-f25a-4a18-a48b-5511e3dfd306";
      fsType = "btrfs";
      options = [ "subvol=@nixos@nixos-config" "relatime" "discard=async" "compress=zstd:1" ];
    };

  fileSystems."/etc/NetworkManager" =
    { device = "/dev/disk/by-uuid/b89c65c8-f25a-4a18-a48b-5511e3dfd306";
      fsType = "btrfs";
      options = [ "subvol=@nixos@networkmanager-config" "relatime" "discard=async" "compress=zstd:1" ];
    };

  fileSystems."/persist" =
    { device = "/dev/disk/by-uuid/b89c65c8-f25a-4a18-a48b-5511e3dfd306";
      fsType = "btrfs";
      options = [ "subvol=@nixos@persist" "relatime" "discard=async" "compress=zstd:1" ];
      neededForBoot = true;
    };

  fileSystems."/root" =
    { device = "/dev/disk/by-uuid/b89c65c8-f25a-4a18-a48b-5511e3dfd306";
      fsType = "btrfs";
      options = [ "subvol=@nixos@root-user" "relatime" "discard=async" "compress=zstd:1" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/ebb5a62f-3403-4bf0-94e1-ea85bf2ca6ae";
      fsType = "btrfs";
      options = [ "subvol=@nixos@home" "relatime" "discard=async" "compress=zstd" ];
    };

  fileSystems."/var/lib/plex" =
    { device = "/dev/disk/by-uuid/b89c65c8-f25a-4a18-a48b-5511e3dfd306";
      fsType = "btrfs";
      options = [ "subvol=@plexdata" "relatime" "discard=async" "compress=zstd:1" ];
    };

  fileSystems."/var/lib/libvirt/images" =
    { device = "/dev/disk/by-uuid/b89c65c8-f25a-4a18-a48b-5511e3dfd306";
      fsType = "btrfs";
      options = [ "subvol=@vm-images" "relatime" "discard=async" "compress=zstd:1" ];
    };

  fileSystems."/mnt/btrfs_pool01" =
    { device = "/dev/disk/by-uuid/b89c65c8-f25a-4a18-a48b-5511e3dfd306";
      fsType = "btrfs";
      options = [ "subvol=/" "relatime" "discard=async" "compress=zstd:1" ];
    };

  fileSystems."/mnt/btrfs_pool02" =
    { device = "/dev/disk/by-uuid/ebb5a62f-3403-4bf0-94e1-ea85bf2ca6ae";
      fsType = "btrfs";
      options = [ "subvol=/" "relatime" "discard=async" "compress=zstd" ];
    };

  fileSystems."/mnt/btrfs_pool03" =
    { device = "/dev/disk/by-uuid/f7eef4ee-4f91-491b-aefe-cccb226ae6a6";
      fsType = "btrfs";
      options = [ "subvol=/" "relatime" "discard=async" "compress=zstd:10" ];
    };

  fileSystems."/mnt/backup/internal" =
    { device = "/dev/disk/by-uuid/fe0229f2-60d3-4cbc-aa92-772f685ecfbe";
      fsType = "btrfs";
      options = [ "subvol=@backup" "relatime" "discard=async" "compress=zstd:10" ];
    };

  fileSystems."/mnt/backup/128Gext" =
    { device = "/dev/disk/by-uuid/82a75835-a541-4976-bc10-d643a69169b6";
      fsType = "btrfs";
      options = [ "subvol=@backup" "relatime" "discard=async" "compress=zstd" "noauto" ];
    };

  fileSystems."/mnt/backup/256Gext" =
    { device = "/dev/disk/by-uuid/7dcad2e8-e127-4a55-9a41-f73c46239e9b";
      fsType = "btrfs";
      options = [ "subvol=@backup" "relatime" "discard=async" "compress=zstd" "noauto" ];
    };

  fileSystems."/srv/public" =
    { device = "/dev/disk/by-uuid/f7eef4ee-4f91-491b-aefe-cccb226ae6a6";
      fsType = "btrfs";
      options = [ "subvol=@public" "relatime" "discard=async" "compress=zstd:10" ];
    };

  fileSystems."/srv/www/html" =
    { device = "/dev/disk/by-uuid/f7eef4ee-4f91-491b-aefe-cccb226ae6a6";
      fsType = "btrfs";
      options = [ "subvol=@html" "relatime" "discard=async" "compress=zstd:10" ];
    };

  fileSystems."/srv/samba" =
    { device = "/dev/disk/by-uuid/f7eef4ee-4f91-491b-aefe-cccb226ae6a6";
      fsType = "btrfs";
      options = [ "subvol=@samba" "relatime" "discard=async" "compress=zstd:10" ];
    };

  fileSystems."/srv/sftp" =
    { device = "/dev/disk/by-uuid/f7eef4ee-4f91-491b-aefe-cccb226ae6a6";
      fsType = "btrfs";
      options = [ "subvol=@sftp" "relatime" "discard=async" "compress=zstd:10" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # this folder is where the files will be stored (don't put it in tmpfs)
  environment.persistence."/persist" = {
    hideMounts = true;
    directories = [
      "/etc/ssh"
      "/var/log"
      "/var/lib/cups"
      "/var/lib/fprint"
      "/var/db/sudo/lectured"
    ];
    files = [
      "/etc/machine-id"
      "/etc/nix/id_rsa"
      "/var/lib/logrotate.status"
    ];
  };
}
